config/routes.rb
Rails.application.routes.draw do
  resources :rss_feeds do 
    collection do
      get "recent_feeds", as: :recent_feeds
    end
  end
  
  

  root 'rss_feeds#recent_feeds'

end

app/models/concerns/rss_feedable.rb
require 'rss'
require 'open-uri'

module RssFeedable

  module ClassMethods
      
  end

  module InstanceMethods
    def recent_feeds!
      fetch_recent_feed! if @items.blank?
    end
    
    def fetch_recent_feed!
      
      open(url) do |rss|
        raw_feed = RSS::Parser.parse(rss)
        
        self.name = raw_feed.channel.title rescue nil
        
        @items ||= []
        raw_feed.items.each do |item|
          @items << build_feed_item(item)
        end
      end
    end
    
    def build_feed_item(raw_item)
      item = RssItem.new
      item.title = raw_item.title
      item.body = raw_item.description
      item.link = raw_item.link
      item.published_date = raw_item.date
      
      item
    end
  end

  def self.included(receiver)
    receiver.extend         ClassMethods
    receiver.send :include, InstanceMethods
  end
end

app/models/rss_feed.rb
class RssFeed < ActiveRecord::Base
  include RssFeedable
  
  validates_format_of :url, :with => URI::regexp(%w(http https))
  attr_accessor :items, :published_date
  
  before_save :fetch_recent_feed!
  
  belongs_to :user
  
  scope :user_scope, ->(user) { where(user_id: user.id) }
  
  def initialize(opts={})
      @items = []
      super
  end
end

app/models/rss_item.rb
class RssItem
  attr_accessor :title, :published_date, :body, :link
  
  def initialize()
    
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :rss_feeds
end

app/controllers/application_controller.rb
require 'securerandom'

class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  #protect_from_forgery with: :exception
  protect_from_forgery with: :null_session
  
  before_action :user_cookies!, :current_user
  
  #get/set user cookie
  def user_cookies!
    cookies[:user] ||= secret_tocken
  end
  
  #get logged in user
  def current_user
    @current_user ||= User.find_or_create_by(secret: cookies[:user])
  end
  
  def secret_tocken
    begin 
      secret = SecureRandom.hex(20)
    end while User.where(secret: secret).last #find unused token
    secret
  end
end

app/controllers/rss_feeds_controller.rb
class RssFeedsController < ApplicationController
  before_action :set_rss_feed, only: [:show, :edit, :update, :destroy]

  # GET /rss_feeds
  # GET /rss_feeds.json
  def index
    @rss_feeds = RssFeed.user_scope(current_user).all
  end

  # GET /rss_feeds/1
  # GET /rss_feeds/1.json
  def show
  end

  # GET /rss_feeds/new
  def new
    @rss_feed = RssFeed.new
  end

  # GET /rss_feeds/1/edit
  def edit
  end

  # POST /rss_feeds
  # POST /rss_feeds.json
  def create
    @rss_feed = RssFeed.new(rss_feed_params)
    @rss_feed.user = @current_user
    
    respond_to do |format|
      if @rss_feed.save
        format.html { redirect_to rss_feeds_url, notice: 'Rss feed was successfully created.' }
        format.json { render :show, status: :created, location: @rss_feed }
      else
        format.html { render :new }
        format.json { render json: @rss_feed.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rss_feeds/1
  # PATCH/PUT /rss_feeds/1.json
  def update
    respond_to do |format|
      if @rss_feed.update(rss_feed_params)
        format.html { redirect_to rss_feeds_url, notice: 'Rss feed was successfully updated.' }
        format.json { render :show, status: :ok, location: @rss_feed }
      else
        format.html { render :edit }
        format.json { render json: @rss_feed.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rss_feeds/1
  # DELETE /rss_feeds/1.json
  def destroy
    @rss_feed.destroy
    respond_to do |format|
      format.html { redirect_to rss_feeds_url, notice: 'Rss feed was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def recent_feeds
     @rss_feeds = RssFeed.user_scope(current_user).all
     @rss_feeds.map(&:recent_feeds!)
     @items = @rss_feeds.map(&:items).flatten.compact.sort{|i1, i2| i2.published_date <=> i1.published_date}
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rss_feed
      @rss_feed = RssFeed.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rss_feed_params
      params.require(:rss_feed).permit(:name, :url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/rss_channels_helper.rb
module RssChannelsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>SB Admin - Bootstrap Admin Template</title>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => false %>


    <!-- Custom Fonts -->
    <link href="/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

    <div id="wrapper">

        <!-- Navigation -->
        <%= render partial: "shared/nav" %>

        <div id="page-wrapper">

            <div class="container-fluid">
              <%= yield %>
            </div>
            <!-- /.container-fluid -->

        </div>
        <!-- /#page-wrapper -->

    </div>
    <!-- /#wrapper -->

    <!-- jQuery -->
   <%= javascript_include_tag 'application', 'data-turbolinks-track' => false %>

</body>

</html>

app/views/rss_feeds/_form.html.erb
<div class="row">
  <div class="col-lg-6">
    <%= form_for(@rss_feed, :role => "form") do |f| %>
      <% if @rss_feed.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@rss_feed.errors.count, "error") %> prohibited this rss_feed from being saved:</h2>

          <ul>
          <% @rss_feed.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-group">
        <%= f.label :url %><br>
        <%= f.text_field :url, class: "form-control" %>
        <p class="help-block">http://example.com/rss</p>
      </div>
      <div class="form-group">
        <%= f.submit 'Submit', class: "btn btn-primary" %>
        <%= link_to 'Back', rss_feeds_path, class: "btn btn-default" %>
      </div>
    <% end %>
  </div>
</div>

app/views/rss_feeds/edit.html.erb
<!-- Page Heading -->
<div class="row">
  <div class="col-lg-12">
    <h1 class="page-header">
      Edit Feed Channel
    </h1>
    <ol class="breadcrumb">
      <li>
        <i class="fa fa-fw fa-wrench"></i>
        <%= link_to "Manage Feeds", rss_feeds_path %>
      </li>
      <li class="active">
        <i class="fa fa-edit"></i> Edit
      </li>
    </ol>
  </div>
</div>
<!-- /.row -->

<%= render 'form' %>

app/views/rss_feeds/index.html.erb
<div class="row">
  <div class="col-lg-12">
    <h1 class="page-header">
      MANAGE FEEDS
    </h1>
    <ol class="breadcrumb">
      <li class="active">
        <i class="fa fa-fw fa-wrench"></i> MANAGE FEEDS
      </li>
    </ol>
  </div>
</div>

<div class="row">
  <div class="col-lg-12">
    <% unless @rss_feeds.blank? %>
      <div class="table-responsive">
      <table class="table table-bordered table-hover table-striped">
        <thead>
          <tr>
            <th>Name</th>
            <th>URL</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @rss_feeds.each do |rss_feed| %>
          <tr>
            <td><%= rss_feed.name %></td>
            <td><%= link_to rss_feed.url, rss_feed.url %></td>
            <td>
              <i class="fa fa-edit"></i> 
              <%= link_to 'Edit', edit_rss_feed_path(rss_feed) %></td>
            <td>
              <i class="fa fa-trash red"></i> 
              <%= link_to 'Destroy', rss_feed_path(rss_feed), method: :delete, data: { confirm: 'Are you sure?' } %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <% end %>
    <br>
    <%= link_to new_rss_feed_path, class: "btn btn-default" do %>
      <i class="fa fa-plus"></i> New RSS FEED
    <% end %>
    <br><br>
  </div>
</div>

app/views/rss_feeds/new.html.erb
<!-- Page Heading -->
<div class="row">
  <div class="col-lg-12">
    <h1 class="page-header">
      New Feed Channel
    </h1>
    <ol class="breadcrumb">
      <li>
        <i class="fa fa-fw fa-wrench"></i>
        <%= link_to "Manage Feeds", rss_feeds_path %>
      </li>
      <li class="active">
        <i class="fa fa-edit"></i> New
      </li>
    </ol>
  </div>
</div>
<!-- /.row -->

<%= render 'form' %>

app/views/rss_feeds/recent_feeds.html.erb
<div class="row">
  <div class="col-lg-12">
    <h1 class="page-header">
      Live Feeds
    </h1>
    <ol class="breadcrumb">
      <li class="active">
        <i class="fa fa-rss"></i> Live Feeds
      </li>
    </ol>
  </div>
</div>

<div class="row">
  <div class="col-lg-12">
    <div class="panel panel-default">
      <div class="panel-heading"></div>
      <div class="panel-body">
        <% if @items.blank? %>
          <div class="text-center">
            <span>No feeds to show</span>
          </div>
        <% end %>
        <ul class="list-group">
          <% @items.each do |item| %>
            <li class="list-group-item">
              <span class="badge"><%= distance_of_time_in_words_to_now(item.published_date) %> ago</span>
              <%= link_to item.title, item.link %> 
            </li>
          <% end %>
          
        </ul>
      </div>
    </div>
    <br>
    <br><br>
  </div>
</div>

app/views/rss_feeds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @rss_feed.name %>
</p>

<p>
  <strong>Url:</strong>
  <%= @rss_feed.url %>
</p>

<%= link_to 'Edit', edit_rss_feed_path(@rss_feed) %> |
<%= link_to 'Back', rss_feeds_path %>

app/views/shared/_nav.html.erb
<!-- Navigation -->
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="/">Live Feeds</a>
  </div>
  <!-- Top Menu Items -->
  <ul class="nav navbar-right top-nav">
    <li class="dropdown">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-envelope"></i> <b class="caret"></b></a>
      <ul class="dropdown-menu message-dropdown">
        <li class="message-preview">
          <a href="#">
            <div class="media">
              <span class="pull-left">
                <img class="media-object" src="http://placehold.it/50x50" alt="">
              </span>
              <div class="media-body">
                <h5 class="media-heading"><strong>John Smith</strong>
                </h5>
                <p class="small text-muted"><i class="fa fa-clock-o"></i> Yesterday at 4:32 PM</p>
                <p>Lorem ipsum dolor sit amet, consectetur...</p>
              </div>
            </div>
          </a>
        </li>
        <li class="message-preview">
          <a href="#">
            <div class="media">
              <span class="pull-left">
                <img class="media-object" src="http://placehold.it/50x50" alt="">
              </span>
              <div class="media-body">
                <h5 class="media-heading"><strong>John Smith</strong>
                </h5>
                <p class="small text-muted"><i class="fa fa-clock-o"></i> Yesterday at 4:32 PM</p>
                <p>Lorem ipsum dolor sit amet, consectetur...</p>
              </div>
            </div>
          </a>
        </li>
        <li class="message-preview">
          <a href="#">
            <div class="media">
              <span class="pull-left">
                <img class="media-object" src="http://placehold.it/50x50" alt="">
              </span>
              <div class="media-body">
                <h5 class="media-heading"><strong>John Smith</strong>
                </h5>
                <p class="small text-muted"><i class="fa fa-clock-o"></i> Yesterday at 4:32 PM</p>
                <p>Lorem ipsum dolor sit amet, consectetur...</p>
              </div>
            </div>
          </a>
        </li>
        <li class="message-footer">
          <a href="#">Read All New Messages</a>
        </li>
      </ul>
    </li>
    <li class="dropdown">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-bell"></i> <b class="caret"></b></a>
      <ul class="dropdown-menu alert-dropdown">
        <li>
          <a href="#">Alert Name <span class="label label-default">Alert Badge</span></a>
        </li>
        <li>
          <a href="#">Alert Name <span class="label label-primary">Alert Badge</span></a>
        </li>
        <li>
          <a href="#">Alert Name <span class="label label-success">Alert Badge</span></a>
        </li>
        <li>
          <a href="#">Alert Name <span class="label label-info">Alert Badge</span></a>
        </li>
        <li>
          <a href="#">Alert Name <span class="label label-warning">Alert Badge</span></a>
        </li>
        <li>
          <a href="#">Alert Name <span class="label label-danger">Alert Badge</span></a>
        </li>
        <li class="divider"></li>
        <li>
          <a href="#">View All</a>
        </li>
      </ul>
    </li>
    <!--<li class="dropdown">-->
    <!--  <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-user"></i> John Smith <b class="caret"></b></a>-->
    <!--  <ul class="dropdown-menu">-->
    <!--    <li>-->
    <!--      <a href="#"><i class="fa fa-fw fa-user"></i> Profile</a>-->
    <!--    </li>-->
    <!--    <li>-->
    <!--      <a href="#"><i class="fa fa-fw fa-envelope"></i> Inbox</a>-->
    <!--    </li>-->
    <!--    <li>-->
    <!--      <a href="#"><i class="fa fa-fw fa-gear"></i> Settings</a>-->
    <!--    </li>-->
    <!--    <li class="divider"></li>-->
    <!--    <li>-->
    <!--      <a href="#"><i class="fa fa-fw fa-power-off"></i> Log Out</a>-->
    <!--    </li>-->
    <!--  </ul>-->
    <!--</li>-->
  </ul>
  <!-- Sidebar Menu Items - These collapse to the responsive navigation menu on small screens -->
  <div class="collapse navbar-collapse navbar-ex1-collapse">
    <ul class="nav navbar-nav side-nav">
      <li class="<%= 'active' if params[:action] == "recent_feeds" %>">
        <a href="/"><i class="fa fa-fw fa-rss"></i> Live Feeds</a>
      </li>
      <li class="<%= 'active' if params[:action] != "recent_feeds" %>">
        <%= link_to rss_feeds_path do %>
          <i class="fa fa-fw fa-wrench"></i> Manage Feeds
        <% end %>
      </li>
    </ul>
  </div>
  <!-- /.navbar-collapse -->
</nav>